Added arm64 support; change tsMuxeR build to be native alpine
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

diff --git a/Dockerfile.10-alpine b/Dockerfile.10-alpine
--- a/Dockerfile.10-alpine
+++ b/Dockerfile.10-alpine
@@ -1,39 +1,47 @@
-# build tsmuxer
-FROM ubuntu:18.04
-COPY tsmuxer-builder.sh /tmp/tsmuxer-builder.sh
-RUN /tmp/tsmuxer-builder.sh /tmp/ /opt/ums/linux
+# build tsmuxer (we must use alpine 3.11 because ninja doesn't exist in 3.12 and above)
+FROM alpine:3.11
+
+# install build dependencies
+RUN apk add --no-cache build-base bzip2-static cmake file freetype-static freetype-dev g++ git libc6-compat libpng-static ninja zlib-dev zlib-static
+
+# copy in build script
+COPY build-tsmuxer.sh /
+
+# build tsMuxeR
+RUN /build-tsmuxer.sh
+
 
 # build UMS image
-FROM alpine:3.12
+FROM alpine:latest
 MAINTAINER Matt Bentley <mbentley@mbentley.net>
 
 ENV UMS_PROFILE=/opt/ums/UMS.conf \
   JAVA_OPTS="-XX:+UnlockExperimentalVMOptions"
 
 # install dependencies per https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions
-# get latest release number and use that to install UMS; fail to install if version is not 9.x
+# get latest release number and use that to install UMS; fail to install if version is not 10.x
 RUN echo '@edge https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories &&\
   apk add --no-cache coreutils flac jq gosu@edge mediainfo mplayer openjdk8-jre vlc &&\
   UMSVER=$(wget -q -O - https://api.github.com/repos/UniversalMediaServer/UniversalMediaServer/releases/latest | jq -r .name) &&\
+  MYARCH="$(arch)" &&\
+  if [ "${MYARCH}" = "x86_64" ]; then UMSARCH="x86_64"; elif [ "${MYARCH}" = "arm64" ] || [ "${MYARCH}" = "aarch64" ]; then UMSARCH="arm64"; else echo "unsupported archtecture"; exit 1; fi &&\
   apk del --purge --no-cache jq &&\
   if [ "$(echo $UMSVER | awk -F '.' '{print $1}')" -ne "10" ]; then echo "Latest version number is no longer 10"; exit 1; fi &&\
-  wget "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/${UMSVER}/UMS-${UMSVER}-x86_64.tgz" -O /opt/UMS-${UMSVER}.tgz &&\
+  wget "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/${UMSVER}/UMS-${UMSVER}-${UMSARCH}.tgz" -O /opt/UMS-${UMSVER}.tgz &&\
   cd /opt &&\
   tar zxf UMS-${UMSVER}.tgz &&\
   rm UMS-${UMSVER}.tgz &&\
   mv ums-${UMSVER} ums &&\
-  rm -rf /opt/ums/jre15 &&\
+  rm -rf /opt/ums/jre* &&\
   rm /opt/ums/linux/tsMuxeR* &&\
-  ln -s /usr/lib/jvm/java-1.8-openjdk/jre /opt/ums/jre15 &&\
   mkdir /opt/ums/database /opt/ums/data &&\
   addgroup -g 500 ums &&\
   adduser -u 500 -G ums -h /opt/ums -D ums &&\
   chown -R ums:ums /opt/ums &&\
-  rm -rf /media/* &&\
-  rm -rf /opt/ums/jre14
+  rm -rf /media/*
 
 # bring over tsmuxer
-COPY --from=0 /tmp/tsmuxer-install /
+COPY --from=0 /tsMuxer/bin/tsMuxeR /opt/ums/linux/tsMuxeR
 
 # add the entrypoint
 COPY entrypoint.sh /entrypoint.sh
