Skip from 12 to 13
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

diff --git a/Dockerfile.13-debian b/Dockerfile.13-debian
--- a/Dockerfile.13-debian
+++ b/Dockerfile.13-debian
@@ -19,11 +19,11 @@ ENV UMS_PROFILE=/opt/ums/UMS.conf \
 # add build arg for cache busting
 ARG UMSVER
 
-# get latest release number and use that to install UMS; fail to install if version is not 12.x
+# get latest release number and use that to install UMS; fail to install if version is not 13.x
 RUN apt-get update &&\
   apt-get install -y jq &&\
   UMSVER=$(if [ -z "${UMSVER}" ]; then wget -q -O - https://api.github.com/repos/UniversalMediaServer/UniversalMediaServer/releases/latest | jq -r .name; else echo "${UMSVER}"; fi) &&\
-  if [ "$(echo $UMSVER | awk -F '.' '{print $1}')" -ne "12" ]; then echo "Latest version number is no longer 12"; exit 1; fi &&\
+  if [ "$(echo $UMSVER | awk -F '.' '{print $1}')" -ne "13" ]; then echo "Latest version number is no longer 13"; exit 1; fi &&\
   wget -nv "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/${UMSVER}/UMS-${UMSVER}-x86_64.tgz" -O /opt/UMS-${UMSVER}.tgz &&\
   cd /opt &&\
   tar zxf UMS-${UMSVER}.tgz &&\
